// <auto-generated />
using System;
using DbModel;
//using CSharpParser.model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrations.SqliteMigrations
{
  [DbContext(typeof(CsharpDbContext))]
  partial class SqliteDbContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

      modelBuilder.Entity("CSharpParser.model.CsharpAstNode", b =>
          {
            b.Property<ulong>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<int>("Accessibility")
                      .HasColumnType("INTEGER");

            b.Property<int>("AstSymbolType")
                      .HasColumnType("INTEGER");

            b.Property<int>("AstType")
                      .HasColumnType("INTEGER");

            b.Property<string>("AstValue")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<long>("Location_range_end_column")
                      .HasColumnType("INTEGER");

            b.Property<long>("Location_range_end_line")
                      .HasColumnType("INTEGER");

            b.Property<long>("Location_range_start_column")
                      .HasColumnType("INTEGER");

            b.Property<long>("Location_range_start_line")
                      .HasColumnType("INTEGER");

            b.Property<string>("Path")
                      .HasColumnType("TEXT");

            b.Property<ushort>("RawKind")
                      .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.ToTable("CsharpAstNodes");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpClass", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<int>("ClassType")
                      .HasColumnType("INTEGER");

            b.Property<long?>("CsharpNamespaceId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("CsharpNamespaceId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpClasses");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEnum", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<long?>("CsharpNamespaceId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("CsharpNamespaceId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpEnums");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEnumMember", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<long?>("CsharpEnumId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<int>("EqualsValue")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("CsharpEnumId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpEnumMembers");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEtcEntity", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<ulong>("DeclaratorNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<int>("EtcEntityType")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.Property<string>("QualifiedType")
                      .HasColumnType("TEXT");

            b.Property<long>("TypeHash")
                      .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpEtcEntitys");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpMethod", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<int>("MethodType")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.Property<string>("QualifiedType")
                      .HasColumnType("TEXT");

            b.Property<long>("TypeHash")
                      .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpMethods");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpNamespace", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpNamespaces");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpStruct", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<long?>("CsharpNamespaceId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("CsharpNamespaceId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpStructs");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpVariable", b =>
          {
            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("INTEGER");

            b.Property<ulong?>("AstNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("DocumentationCommentXML")
                      .HasColumnType("TEXT");

            b.Property<long>("EntityHash")
                      .HasColumnType("INTEGER");

            b.Property<string>("Name")
                      .HasColumnType("TEXT");

            b.Property<ulong?>("ParentNodeId")
                      .HasColumnType("INTEGER");

            b.Property<string>("QualifiedName")
                      .HasColumnType("TEXT");

            b.Property<string>("QualifiedType")
                      .HasColumnType("TEXT");

            b.Property<long>("TypeHash")
                      .HasColumnType("INTEGER");

            b.Property<int>("VariableType")
                      .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("AstNodeId");

            b.HasIndex("ParentNodeId");

            b.ToTable("CsharpVariables");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpClass", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpNamespace", "CsharpNamespace")
                      .WithMany()
                      .HasForeignKey("CsharpNamespaceId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("CsharpNamespace");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEnum", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpNamespace", "CsharpNamespace")
                      .WithMany()
                      .HasForeignKey("CsharpNamespaceId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("CsharpNamespace");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEnumMember", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpEnum", null)
                      .WithMany("CsharpEnumMembers")
                      .HasForeignKey("CsharpEnumId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEtcEntity", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpMethod", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpNamespace", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpStruct", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpNamespace", "CsharpNamespace")
                      .WithMany()
                      .HasForeignKey("CsharpNamespaceId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("CsharpNamespace");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpVariable", b =>
          {
            b.HasOne("CSharpParser.model.CsharpAstNode", "AstNode")
                      .WithMany()
                      .HasForeignKey("AstNodeId");

            b.HasOne("CSharpParser.model.CsharpAstNode", "ParentNode")
                      .WithMany()
                      .HasForeignKey("ParentNodeId");

            b.Navigation("AstNode");

            b.Navigation("ParentNode");
          });

      modelBuilder.Entity("CSharpParser.model.CsharpEnum", b =>
          {
            b.Navigation("CsharpEnumMembers");
          });
#pragma warning restore 612, 618
    }
  }
}
