/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum FileParseStatus
{
  Nothing = 0,
  OnlyInSearchIndex = 1,
  PartiallyParsed = 2,
  FullyParsed = 3,
}
