/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



/// <summary>
/// ********************
///  General Exceptions *
/// ********************
/// </summary>
public partial class InvalidId : TException, TBase
{
  private string _msg;
  private string _fid;
  private string _nodeid;

  public string Msg
  {
    get
    {
      return _msg;
    }
    set
    {
      __isset.msg = true;
      this._msg = value;
    }
  }

  public string Fid
  {
    get
    {
      return _fid;
    }
    set
    {
      __isset.fid = true;
      this._fid = value;
    }
  }

  public string Nodeid
  {
    get
    {
      return _nodeid;
    }
    set
    {
      __isset.nodeid = true;
      this._nodeid = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool msg;
    public bool fid;
    public bool nodeid;
  }

  public InvalidId()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String)
            {
              Msg = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.String)
            {
              Fid = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 3:
            if (field.Type == TType.String)
            {
              Nodeid = await iprot.ReadStringAsync(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("InvalidId");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (Msg != null && __isset.msg)
      {
        field.Name = "msg";
        field.Type = TType.String;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Msg, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Fid != null && __isset.fid)
      {
        field.Name = "fid";
        field.Type = TType.String;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Fid, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Nodeid != null && __isset.nodeid)
      {
        field.Name = "nodeid";
        field.Type = TType.String;
        field.ID = 3;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteStringAsync(Nodeid, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as InvalidId;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.msg == other.__isset.msg) && ((!__isset.msg) || (System.Object.Equals(Msg, other.Msg))))
      && ((__isset.fid == other.__isset.fid) && ((!__isset.fid) || (System.Object.Equals(Fid, other.Fid))))
      && ((__isset.nodeid == other.__isset.nodeid) && ((!__isset.nodeid) || (System.Object.Equals(Nodeid, other.Nodeid))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.msg)
        hashcode = (hashcode * 397) + Msg.GetHashCode();
      if(__isset.fid)
        hashcode = (hashcode * 397) + Fid.GetHashCode();
      if(__isset.nodeid)
        hashcode = (hashcode * 397) + Nodeid.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("InvalidId(");
    bool __first = true;
    if (Msg != null && __isset.msg)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Msg: ");
      sb.Append(Msg);
    }
    if (Fid != null && __isset.fid)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Fid: ");
      sb.Append(Fid);
    }
    if (Nodeid != null && __isset.nodeid)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Nodeid: ");
      sb.Append(Nodeid);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

