/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum MessageType
{
  Unknown = 0,
  Error = 1,
  FatalError = 2,
  Warning = 3,
  Note = 4,
  CodingRule = 5,
}
