/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



/// <summary>
/// ****************************
///  File positions & locations *
/// ****************************
/// </summary>
public partial class Position : TBase
{
  private int _line;
  private int _column;

  public int Line
  {
    get
    {
      return _line;
    }
    set
    {
      __isset.line = true;
      this._line = value;
    }
  }

  public int Column
  {
    get
    {
      return _column;
    }
    set
    {
      __isset.column = true;
      this._column = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool line;
    public bool column;
  }

  public Position()
  {
    this._line = -1;
    this.__isset.line = true;
    this._column = -1;
    this.__isset.column = true;
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32)
            {
              Line = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.I32)
            {
              Column = await iprot.ReadI32Async(cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("Position");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (__isset.line)
      {
        field.Name = "line";
        field.Type = TType.I32;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async(Line, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (__isset.column)
      {
        field.Name = "column";
        field.Type = TType.I32;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await oprot.WriteI32Async(Column, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as Position;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.line == other.__isset.line) && ((!__isset.line) || (System.Object.Equals(Line, other.Line))))
      && ((__isset.column == other.__isset.column) && ((!__isset.column) || (System.Object.Equals(Column, other.Column))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.line)
        hashcode = (hashcode * 397) + Line.GetHashCode();
      if(__isset.column)
        hashcode = (hashcode * 397) + Column.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("Position(");
    bool __first = true;
    if (__isset.line)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Line: ");
      sb.Append(Line);
    }
    if (__isset.column)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Column: ");
      sb.Append(Column);
    }
    sb.Append(")");
    return sb.ToString();
  }
}

