/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;



public partial class Range : TBase
{
  private Position _startpos;
  private Position _endpos;

  public Position Startpos
  {
    get
    {
      return _startpos;
    }
    set
    {
      __isset.startpos = true;
      this._startpos = value;
    }
  }

  public Position Endpos
  {
    get
    {
      return _endpos;
    }
    set
    {
      __isset.endpos = true;
      this._endpos = value;
    }
  }


  public Isset __isset;
  public struct Isset
  {
    public bool startpos;
    public bool endpos;
  }

  public Range()
  {
  }

  public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      await iprot.ReadStructBeginAsync(cancellationToken);
      while (true)
      {
        field = await iprot.ReadFieldBeginAsync(cancellationToken);
        if (field.Type == TType.Stop)
        {
          break;
        }

        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct)
            {
              Startpos = new Position();
              await Startpos.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          case 2:
            if (field.Type == TType.Struct)
            {
              Endpos = new Position();
              await Endpos.ReadAsync(iprot, cancellationToken);
            }
            else
            {
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            }
            break;
          default: 
            await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
            break;
        }

        await iprot.ReadFieldEndAsync(cancellationToken);
      }

      await iprot.ReadStructEndAsync(cancellationToken);
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
  {
    oprot.IncrementRecursionDepth();
    try
    {
      var struc = new TStruct("Range");
      await oprot.WriteStructBeginAsync(struc, cancellationToken);
      var field = new TField();
      if (Startpos != null && __isset.startpos)
      {
        field.Name = "startpos";
        field.Type = TType.Struct;
        field.ID = 1;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Startpos.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      if (Endpos != null && __isset.endpos)
      {
        field.Name = "endpos";
        field.Type = TType.Struct;
        field.ID = 2;
        await oprot.WriteFieldBeginAsync(field, cancellationToken);
        await Endpos.WriteAsync(oprot, cancellationToken);
        await oprot.WriteFieldEndAsync(cancellationToken);
      }
      await oprot.WriteFieldStopAsync(cancellationToken);
      await oprot.WriteStructEndAsync(cancellationToken);
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override bool Equals(object that)
  {
    var other = that as Range;
    if (other == null) return false;
    if (ReferenceEquals(this, other)) return true;
    return ((__isset.startpos == other.__isset.startpos) && ((!__isset.startpos) || (System.Object.Equals(Startpos, other.Startpos))))
      && ((__isset.endpos == other.__isset.endpos) && ((!__isset.endpos) || (System.Object.Equals(Endpos, other.Endpos))));
  }

  public override int GetHashCode() {
    int hashcode = 157;
    unchecked {
      if(__isset.startpos)
        hashcode = (hashcode * 397) + Startpos.GetHashCode();
      if(__isset.endpos)
        hashcode = (hashcode * 397) + Endpos.GetHashCode();
    }
    return hashcode;
  }

  public override string ToString()
  {
    var sb = new StringBuilder("Range(");
    bool __first = true;
    if (Startpos != null && __isset.startpos)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Startpos: ");
      sb.Append(Startpos== null ? "<null>" : Startpos.ToString());
    }
    if (Endpos != null && __isset.endpos)
    {
      if(!__first) { sb.Append(", "); }
      __first = false;
      sb.Append("Endpos: ");
      sb.Append(Endpos== null ? "<null>" : Endpos.ToString());
    }
    sb.Append(")");
    return sb.ToString();
  }
}

