#!/usr/bin/env bash

ending() 
{
  finish=true
  kill $pid
}

trap ending SIGINT

ulimit -c unlimited &> /dev/null

if [ -z $CODECOMPASS_HOME ]; then
  CODECOMPASS_HOME=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
  CODECOMPASS_HOME=$(readlink -f "$CODECOMPASS_HOME/..")
fi

export LD_LIBRARY_PATH=$CODECOMPASS_HOME/lib:$CODECOMPASS_HOME/lib/serviceplugin:$LD_LIBRARY_PATH
export CLASSPATH=$CODECOMPASS_HOME/lib/java/*
export MAGIC=$CODECOMPASS_HOME/share/misc/magic.mgc

while true; do
  $@ &
  pid=$!
  wait $pid
  if [ $? -eq 0 ] || $finish; then break; fi
done
