#!/usr/bin/env bash

finish=false

ending() 
{
  finish=true
  kill $pid
}

trap ending SIGINT SIGTERM

ulimit -c unlimited &> /dev/null

while true; do
  $@ &
  pid=$!
  wait $pid
  if [ $? -eq 0 ] || $finish; then break; fi
done
