/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Thrift;
using Thrift.Collections;

using Thrift.Protocol;
using Thrift.Protocol.Entities;
using Thrift.Protocol.Utilities;
using Thrift.Transport;
using Thrift.Transport.Client;
using Thrift.Transport.Server;
using Thrift.Processor;


namespace language
{

  /// <summary>
  /// Meta information of the AST node (e.g. public, static, virtual etc.)
  /// </summary>
  public partial class SyntaxHighlight : TBase
  {
    private Range _range;
    private string _className;

    public Range Range
    {
      get
      {
        return _range;
      }
      set
      {
        __isset.range = true;
        this._range = value;
      }
    }

    /// <summary>
    /// Source code range of an AST node.
    /// </summary>
    public string ClassName
    {
      get
      {
        return _className;
      }
      set
      {
        __isset.className = true;
        this._className = value;
      }
    }


    public Isset __isset;
    public struct Isset
    {
      public bool range;
      public bool className;
    }

    public SyntaxHighlight()
    {
    }

    public async Task ReadAsync(TProtocol iprot, CancellationToken cancellationToken)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        await iprot.ReadStructBeginAsync(cancellationToken);
        while (true)
        {
          field = await iprot.ReadFieldBeginAsync(cancellationToken);
          if (field.Type == TType.Stop)
          {
            break;
          }

          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct)
              {
                Range = new Range();
                await Range.ReadAsync(iprot, cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            case 2:
              if (field.Type == TType.String)
              {
                ClassName = await iprot.ReadStringAsync(cancellationToken);
              }
              else
              {
                await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              }
              break;
            default: 
              await TProtocolUtil.SkipAsync(iprot, field.Type, cancellationToken);
              break;
          }

          await iprot.ReadFieldEndAsync(cancellationToken);
        }

        await iprot.ReadStructEndAsync(cancellationToken);
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public async Task WriteAsync(TProtocol oprot, CancellationToken cancellationToken)
    {
      oprot.IncrementRecursionDepth();
      try
      {
        var struc = new TStruct("SyntaxHighlight");
        await oprot.WriteStructBeginAsync(struc, cancellationToken);
        var field = new TField();
        if (Range != null && __isset.range)
        {
          field.Name = "range";
          field.Type = TType.Struct;
          field.ID = 1;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await Range.WriteAsync(oprot, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        if (ClassName != null && __isset.className)
        {
          field.Name = "className";
          field.Type = TType.String;
          field.ID = 2;
          await oprot.WriteFieldBeginAsync(field, cancellationToken);
          await oprot.WriteStringAsync(ClassName, cancellationToken);
          await oprot.WriteFieldEndAsync(cancellationToken);
        }
        await oprot.WriteFieldStopAsync(cancellationToken);
        await oprot.WriteStructEndAsync(cancellationToken);
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override bool Equals(object that)
    {
      var other = that as SyntaxHighlight;
      if (other == null) return false;
      if (ReferenceEquals(this, other)) return true;
      return ((__isset.range == other.__isset.range) && ((!__isset.range) || (System.Object.Equals(Range, other.Range))))
        && ((__isset.className == other.__isset.className) && ((!__isset.className) || (System.Object.Equals(ClassName, other.ClassName))));
    }

    public override int GetHashCode() {
      int hashcode = 157;
      unchecked {
        if(__isset.range)
          hashcode = (hashcode * 397) + Range.GetHashCode();
        if(__isset.className)
          hashcode = (hashcode * 397) + ClassName.GetHashCode();
      }
      return hashcode;
    }

    public override string ToString()
    {
      var sb = new StringBuilder("SyntaxHighlight(");
      bool __first = true;
      if (Range != null && __isset.range)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("Range: ");
        sb.Append(Range== null ? "<null>" : Range.ToString());
      }
      if (ClassName != null && __isset.className)
      {
        if(!__first) { sb.Append(", "); }
        __first = false;
        sb.Append("ClassName: ");
        sb.Append(ClassName);
      }
      sb.Append(")");
      return sb.ToString();
    }
  }

}
