// $Id$
// Created by Aron Barath, 2015

#ifndef MODEL_JAVA_JAVAFUNCTIONTYPEPARAMS_H
#define MODEL_JAVA_JAVAFUNCTIONTYPEPARAMS_H

#include <string>
#include <memory>
#include <vector>

#include <odb/core.hxx>
#include <odb/lazy-ptr.hxx>

namespace cc
{
namespace model
{

struct JavaFunction;
struct JavaType;

// This is the join table generated by JPA.
#pragma db object no_id
struct JavaFunction_TypeParams
{
  #pragma db not_null
  odb::lazy_shared_ptr<JavaFunction> function;

  #pragma db not_null
  odb::lazy_shared_ptr<JavaType> param;
};

typedef std::shared_ptr<JavaFunction_TypeParams> JavaFunction_TypeParamsPtr;

} // model
} // cc

#include <model/java/javafunction.h>
#include <model/java/javatype.h>

#endif // MODEL_JAVA_JAVAFUNCTIONTYPEPARAMS_H

